/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orgs/{orgSlug}/programs/{programSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        /**
         * Look up a program for its landing page
         * @description A closed or full program still resolves, carrying the state that lets the
         *     landing page offer a waitlist rather than a 404.
         */
        get: operations["getProgramBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/programs/{programSlug}/form-schema": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        /**
         * Read the published form schema for a role
         * @description Mentors and mentees answer different questions, so the role is required
         *     rather than defaulted.
         *
         *     Returns the currently published version. Publishing a change mints a new
         *     version and leaves submitted applications on the one they were filled
         *     against, so an answer is always readable against the questions that were
         *     actually asked.
         *
         *     Public, because the application form is filled before anyone has an
         *     account.
         */
        get: operations["getFormSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/programs/{programSlug}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an application to a program
         * @description Answers are keyed by field id, taken from the form version named in
         *     `formVersionId`. Fields hidden by a condition are absent rather than
         *     null: a question nobody was shown has no answer.
         */
        post: operations["submitApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        /**
         * Read an application's status
         * @description Backs the "what happens next" screen after submitting.
         *
         *     Access control note: this route is keyed by a raw UUID and requires no
         *     session, which is acceptable for the mocked slice but is a real access
         *     control hole. In production the emailed link carries a signed,
         *     expiring token scoped to this one application, and the raw UUID stops
         *     being a valid credential.
         */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a sign-in link
         * @description Always returns 202, whether or not an account exists for the address.
         *     A 404 here would turn the endpoint into an account-enumeration oracle.
         */
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume a magic-link token and open a session
         * @description Sets the `braid_session` cookie. Tokens are single use.
         */
        post: operations["verifyMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Clears the session cookie. Safe to call without a session.
         */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the current account and its participations
         * @description Every authenticated page depends on this: it resolves the account, the
         *     programs it belongs to, and the role held in each.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** List approved participants in a program */
        get: operations["listRoster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** List matching runs for a program */
        get: operations["listRuns"];
        put?: never;
        /**
         * Start a matching run
         * @description Returns immediately with state `queued`. A run is a stored object with a
         *     lifecycle, not a function call: poll the run to follow it to `drafted`.
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * Read a run, its fairness summary, and its draft pairs
         * @description While the run is `queued` or `running`, `progress` advances from 0 to 1
         *     and `fairnessSummary` is null. Both are populated once it reaches
         *     `drafted`.
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a drafted run
         * @description Irreversible. Converts every draft pair into an active strand and
         *     notifies both sides.
         */
        post: operations["publishRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/strands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** List the strands the current account holds in a program */
        get: operations["listStrands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strands/{strandId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        /** Read one strand */
        get: operations["getStrand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strands/{strandId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        /**
         * Read a strand's message thread
         * @description Newest last. Page backwards with `before`.
         */
        get: operations["listMessages"];
        put?: never;
        /** Send a message to a strand */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @description Stable machine-readable identifier, e.g. `applications_closed`. */
            code: string;
            /** @description Sentence-case text safe to show a person. */
            message: string;
            /** @description Present when the failure belongs to one input. */
            field?: string;
        };
        /** @enum {string} */
        Role: "mentor" | "mentee";
        /** @enum {string} */
        ParticipationStatus: "invited" | "applied" | "approved" | "waitlisted" | "removed";
        /** @enum {string} */
        ApplicationStatus: "submitted" | "under_review" | "approved" | "waitlisted" | "rejected";
        /** @enum {string} */
        ProgramState: "not_yet_open" | "open" | "closed" | "full";
        /** @enum {string} */
        RunState: "queued" | "running" | "drafted" | "published" | "discarded";
        /** @enum {string} */
        StrandState: "draft" | "active" | "paused" | "ended" | "discarded";
        /** @enum {string} */
        OriginMode: "manual" | "self" | "batch";
        /** @enum {string} */
        PriorityBand: "high" | "medium" | "low";
        /** @description One answer to one question. */
        AnswerValue: string | number | boolean | string[];
        /**
         * @description Where the words came from. `self` is typed unprompted; `guided` is the
         *     answer to an elicitation follow-up on the guided completion screen.
         *
         *     Recorded because scoring free text rewards writing fluency, which tracks
         *     schooling and language background. Reports have to be able to ask
         *     whether coverage improved without the guided answers quietly becoming a
         *     ranking feature.
         * @enum {string}
         */
        Provenance: "self" | "guided";
        /**
         * @description One answer on the way in. There is no timestamp: the server stamps it,
         *     because a client-supplied time is not evidence of anything.
         */
        AnswerInput: {
            value: components["schemas"]["AnswerValue"];
            provenance: components["schemas"]["Provenance"];
        };
        /** @description One stored answer, as read back. */
        AnswerRecord: {
            value: components["schemas"]["AnswerValue"];
            provenance: components["schemas"]["Provenance"];
            /** Format: date-time */
            answeredAt: string;
        };
        /** @enum {string} */
        FormFieldType: "short_text" | "long_text" | "single_select" | "multi_select" | "scale" | "number" | "date" | "file" | "consent";
        /**
         * @description `id` is what an answer stores. Labels are editable copy and must never be
         *     the key, or fixing a typo would orphan every answer that used it.
         */
        FormOption: {
            /** Format: uuid */
            id: string;
            label: string;
        };
        FormClause: {
            /** Format: uuid */
            fieldId: string;
            /** @enum {string} */
            operator: "equals" | "not_equals" | "includes" | "is_answered" | "gt" | "lt";
            value?: components["schemas"]["AnswerValue"];
        };
        /**
         * @description Every clause must hold. One level deep on purpose: `any` can be added
         *     beside `all` later without migrating a single stored schema.
         */
        FormCondition: {
            all: components["schemas"]["FormClause"][];
        };
        FormField: {
            /**
             * Format: uuid
             * @description Stable for the life of the question, across versions and across
             *     label edits. Answers are keyed by this and never by the label.
             */
            id: string;
            type: components["schemas"]["FormFieldType"];
            label: string;
            help?: string | null;
            required: boolean;
            /** @description Feeds the similarity score. */
            matching: boolean;
            /** @description Feeds the priority score. */
            equity: boolean;
            /** @description Collected, never scored, visible to the coordinator only. */
            admin: boolean;
            visibleWhen?: components["schemas"]["FormCondition"] | null;
            /** @description Select types only. */
            options?: components["schemas"]["FormOption"][] | null;
            text?: {
                minLength?: number | null;
                maxLength?: number | null;
                placeholder?: string | null;
            } | null;
            number?: {
                min?: number | null;
                max?: number | null;
                step?: number | null;
                unit?: string | null;
            } | null;
            scale?: {
                min: number;
                max: number;
                minLabel?: string | null;
                maxLabel?: string | null;
            } | null;
            date?: {
                /** Format: date */
                min?: string | null;
                /** Format: date */
                max?: string | null;
            } | null;
            file?: {
                accept: string[];
                maxSizeBytes: number;
            } | null;
            consent?: {
                /**
                 * @description The sentence next to the checkbox. Separate from `label`, which
                 *     names the question in the coordinator's list.
                 */
                statement: string;
                /** Format: uri */
                documentUrl?: string | null;
            } | null;
            /** @description Multi select only. */
            selection?: {
                min?: number | null;
                max?: number | null;
            } | null;
        };
        FormSection: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string | null;
            fields: components["schemas"]["FormField"][];
        };
        /**
         * @description The whole published document. Stored as one versioned JSONB blob rather
         *     than normalised rows: it is read whole, written whole, and never queried
         *     field by field.
         */
        FormVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            role: components["schemas"]["Role"];
            version: number;
            /** Format: date-time */
            publishedAt?: string | null;
            sections: components["schemas"]["FormSection"][];
        };
        Organisation: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** Format: uri */
            logoUrl?: string | null;
        };
        ProgramPublic: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            organisation: components["schemas"]["Organisation"];
            description: string;
            state: components["schemas"]["ProgramState"];
            /** Format: date */
            cohortStart?: string | null;
            /** Format: date */
            cohortEnd?: string | null;
            /** Format: date-time */
            applicationsCloseAt?: string | null;
            /** Format: date-time */
            matchingOpensAt?: string | null;
            /** @description Plain words, e.g. "About two hours a month for six months". */
            timeCommitment?: string | null;
            eligibility?: string | null;
            openRoles: components["schemas"]["Role"][];
            mentorCount: number;
            menteeCount: number;
        };
        ApplicationCreate: {
            role: components["schemas"]["Role"];
            name: string;
            /** Format: email */
            email: string;
            /**
             * Format: uuid
             * @description Which published version was on screen. Sent so the server can reject
             *     a submission filled against a version that is no longer current,
             *     rather than storing answers to questions nobody can reconstruct.
             */
            formVersionId: string;
            /**
             * @description Keyed by field id. Answers to fields hidden by a condition are not
             *     sent; the client keeps them locally in case the person toggles back,
             *     but an unasked question has no answer.
             */
            answers: {
                [key: string]: components["schemas"]["AnswerInput"];
            };
        };
        Application: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            programName?: string;
            role: components["schemas"]["Role"];
            name: string;
            /** Format: email */
            email: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            editableUntil?: string | null;
            /** Format: date-time */
            matchingOpensAt?: string | null;
            /**
             * Format: uuid
             * @description The version these answers were filled against. Reading them back
             *     without it would mean guessing which questions were asked.
             */
            formVersionId: string;
            answers: {
                [key: string]: components["schemas"]["AnswerRecord"];
            };
        };
        MagicLinkRequest: {
            /** Format: email */
            email: string;
            /** @description Return the person to this program after verifying. */
            orgSlug?: string;
            programSlug?: string;
        };
        VerifyRequest: {
            token: string;
        };
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            emailVerified: boolean;
            /** Format: uri */
            photoUrl?: string | null;
        };
        ParticipationSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            programName: string;
            organisationName?: string;
            orgSlug: string;
            programSlug: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["ParticipationStatus"];
            /** @default false */
            isCoordinator: boolean;
        };
        Session: {
            account: components["schemas"]["Account"];
            participations: components["schemas"]["ParticipationSummary"][];
        };
        RosterEntry: {
            /**
             * Format: uuid
             * @description The participation id, not the account id.
             */
            id: string;
            account: components["schemas"]["Account"];
            role: components["schemas"]["Role"];
            status: components["schemas"]["ParticipationStatus"];
            matched: boolean;
            /** @description Mentors only. How many mentees they will take. */
            capacity?: number | null;
            /** @description Mentors only. Active strands held. May exceed capacity. */
            load?: number | null;
            profileCompleteness: number;
            /** @description IANA name, e.g. Africa/Lagos. */
            timezone?: string | null;
            /** Format: date-time */
            joinedAt: string;
        };
        RosterPage: {
            items: components["schemas"]["RosterEntry"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PersonRef: {
            /** Format: uuid */
            participationId: string;
            name: string;
            /** Format: uri */
            photoUrl?: string | null;
        };
        MentorLoad: {
            mentor: components["schemas"]["PersonRef"];
            load: number;
            capacity: number;
        };
        /**
         * @description The comparison that makes a run defensible: whether high-priority
         *     mentees came out with match quality comparable to low-priority ones.
         */
        PriorityBandStat: {
            band: components["schemas"]["PriorityBand"];
            menteeCount: number;
            meanScore: number;
            medianScore: number;
        };
        ScoreBucket: {
            rangeStart: number;
            rangeEnd: number;
            count: number;
        };
        FairnessSummary: {
            coverageRate: number;
            matchedCount: number;
            unmatchedCount: number;
            totalMentees: number;
            mentorLoad: components["schemas"]["MentorLoad"][];
            priorityBands: components["schemas"]["PriorityBandStat"][];
            scoreDistribution: components["schemas"]["ScoreBucket"][];
        };
        DraftPair: {
            /** Format: uuid */
            id: string;
            mentee: components["schemas"]["PersonRef"];
            mentor: components["schemas"]["PersonRef"];
            score: number;
            priorityBand: components["schemas"]["PriorityBand"];
        };
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            state: components["schemas"]["RunState"];
            /** @description 0 to 1 while queued or running. 1 once drafted. */
            progress: number;
            recipeVersion?: number;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            publishedAt?: string | null;
            publishedBy?: string | null;
            draftedCount?: number;
            publishedCount?: number;
            coverageRate?: number | null;
        };
        RunDetail: components["schemas"]["Run"] & {
            fairnessSummary?: components["schemas"]["FairnessSummary"] | null;
            pairs: components["schemas"]["DraftPair"][];
            unmatchedCount: number;
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            page: number;
            pageSize: number;
            total: number;
        };
        StrandMember: {
            /** Format: uuid */
            participationId: string;
            name: string;
            role: components["schemas"]["Role"];
            headline?: string | null;
            /** Format: uri */
            photoUrl?: string | null;
            timezone?: string | null;
            skills?: string[];
        };
        MessagePreview: {
            authorName: string;
            body: string;
            /** Format: date-time */
            sentAt: string;
        };
        StrandSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            state: components["schemas"]["StrandState"];
            originMode: components["schemas"]["OriginMode"];
            /** @description Everyone except the current account. */
            members: components["schemas"]["StrandMember"][];
            lastMessage?: components["schemas"]["MessagePreview"] | null;
            /**
             * Format: date-time
             * @description The UI derives the quiet state from this. There is no health enum,
             *     because a quiet strand is not an error and must not render as one.
             */
            lastActivityAt?: string | null;
            unreadCount: number;
            /** Format: date-time */
            nextSessionAt?: string | null;
            /**
             * Format: date-time
             * @description Set when `state` is `ended`. The card names the date, so the
             *     summary has to carry it rather than making the list fetch each
             *     strand to find out when it finished.
             */
            endedAt?: string | null;
        };
        Strand: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            state: components["schemas"]["StrandState"];
            originMode: components["schemas"]["OriginMode"];
            /** @description Every member, including the current account. */
            members: components["schemas"]["StrandMember"][];
            /**
             * @description Why these people were put together. A partial explanation, not the
             *     explanation: in a global assignment the real reason often involves a
             *     third person. Present it as such.
             */
            matchRationale?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            endedAt?: string | null;
        };
        MessageCreate: {
            body: string;
            /**
             * @description Echoed back on the created message so an optimistic send can be
             *     reconciled against the server row instead of duplicated.
             */
            clientToken?: string;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            strandId: string;
            author: components["schemas"]["PersonRef"];
            body: string;
            /** Format: date-time */
            sentAt: string;
            /** @enum {string} */
            deliveryState: "sent" | "delivered";
            clientToken?: string | null;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            /** @description Pass as `before` to fetch the previous page. Null when at the start. */
            nextCursor: string | null;
        };
    };
    responses: {
        /** @description The request failed validation */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description No valid session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Signed in, but not permitted here */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limited */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        OrgSlug: string;
        ProgramSlug: string;
        ProgramId: string;
        RunId: string;
        StrandId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProgramBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The program */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramPublic"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getFormSchema: {
        parameters: {
            query: {
                role: components["schemas"]["Role"];
            };
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published form version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormVersion"];
                };
            };
            /** @description No such program, or no published form for that role */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    submitApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Application received */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Applications are closed, or this email already applied */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The application */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Accepted. A link is sent only if the address has an account. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    verifyMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Session opened */
            200: {
                headers: {
                    /** @example braid_session=…; HttpOnly; Secure; SameSite=Lax; Path=/ */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Token expired or already used */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    /** @example braid_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRoster: {
        parameters: {
            query?: {
                role?: components["schemas"]["Role"];
                status?: components["schemas"]["ParticipationStatus"];
                /** @description Filter to participants who do or do not hold a strand. */
                matched?: boolean;
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the roster */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of runs, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A run is already in progress for this program */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    publishRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Run is not in a publishable state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listStrands: {
        parameters: {
            query?: {
                state?: components["schemas"]["StrandState"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The strands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrandSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getStrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The strand */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strand"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Return messages sent before this message id. */
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Message sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
