/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orgs/{orgSlug}/programs/{programSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        /**
         * Look up a program for its landing page
         * @description A closed or full program still resolves, carrying the state that lets the
         *     landing page offer a waitlist rather than a 404.
         */
        get: operations["getProgramBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/programs/{programSlug}/form-schema": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        /**
         * Read the published form schema for a role
         * @description Mentors and mentees answer different questions, so the role is required
         *     rather than defaulted.
         *
         *     Returns the currently published version. Publishing a change mints a new
         *     version and leaves submitted applications on the one they were filled
         *     against, so an answer is always readable against the questions that were
         *     actually asked.
         *
         *     Public, because the application form is filled before anyone has an
         *     account.
         */
        get: operations["getFormSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/programs/{programSlug}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an application to a program
         * @description Answers are keyed by field id, taken from the form version named in
         *     `formVersionId`. Fields hidden by a condition are absent rather than
         *     null: a question nobody was shown has no answer.
         */
        post: operations["submitApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/programs/{programSlug}/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask to be told when the next round opens
         * @description The action a closed, full or not-yet-open programme offers instead of a
         *     dead end. Always returns 202, for the same reason the magic-link
         *     endpoint does: a different answer for a known address would make this an
         *     enumeration oracle.
         */
        post: operations["joinWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/programs/{programSlug}/application-draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        /** Read a saved draft */
        get: operations["getApplicationDraft"];
        /**
         * Autosave a partly filled application
         * @description Upsert. Omit `draftId` on the first call and the server mints one; the
         *     client holds it and sends it back on every later save.
         *
         *     The draft is reachable by whoever holds the id, which is the same
         *     exposure as `GET /applications/{applicationId}` and is acceptable for
         *     the same reason: it carries no credential and grants nothing beyond the
         *     answers already typed on that device.
         *
         *     Not yet built: emailing a resume link, which architecture 3.2 lists as
         *     an action. Until it exists the id lives only in the browser that started
         *     the form, and the screen says so rather than implying otherwise.
         */
        put: operations["saveApplicationDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        /**
         * Read an application's status
         * @description Backs the "what happens next" screen after submitting.
         *
         *     Access control note: this route is keyed by a raw UUID and requires no
         *     session, which is acceptable for the mocked slice but is a real access
         *     control hole. In production the emailed link carries a signed,
         *     expiring token scoped to this one application, and the raw UUID stops
         *     being a valid credential.
         */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a sign-in link
         * @description Always returns 202, whether or not an account exists for the address.
         *     A 404 here would turn the endpoint into an account-enumeration oracle.
         */
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume a magic-link token and open a session
         * @description Sets the `braid_session` cookie. Tokens are single use.
         */
        post: operations["verifyMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Clears the session cookie. Safe to call without a session.
         */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the current account and its participations
         * @description Every authenticated page depends on this: it resolves the account, the
         *     programs it belongs to, and the role held in each.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/home": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /**
         * Everything the participant home screen puts on the page
         * @description One request, because home answers one question — what should I do right
         *     now — and four round trips to answer it would leave the screen
         *     assembling itself in front of the reader.
         *
         *     Composed for the screen rather than mirroring a table. Architecture 4.1
         *     fixes the contents: next action, active strands, profile completeness,
         *     the coordinator's announcement, and the next milestone. The strands
         *     themselves stay on their own endpoint, because the strands list needs
         *     them too.
         */
        get: operations["getHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** List approved participants in a program */
        get: operations["listRoster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /**
         * Programme health in one response
         * @description The screen a coordinator opens daily during a live cohort. The attention
         *     list is the point of it: counts alone say how things are, and the list
         *     says what to do about them.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/strand-monitor": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** Every strand in the programme, with its health */
        get: operations["monitorStrands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strands/{strandId}/nudge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the nudge template to a strand
         * @description Uses the programme's nudge template rather than free text, so the
         *     wording is the one the coordinator already reviewed and every quiet
         *     strand gets the same message.
         */
        post: operations["nudgeStrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strands/{strandId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Pause, resume or end a strand
         * @description Ending is one way. A strand that ended keeps its conversation and stays
         *     readable to both sides; it is not deleted, because the record of what
         *     was said is the thing participants come back for.
         */
        put: operations["setStrandState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** Read the programme arc */
        get: operations["listProgramMilestones"];
        /**
         * Replace the programme arc
         * @description Written whole rather than per milestone. The arc is one thing a
         *     coordinator edits as a shape — adding a step changes what comes after
         *     it — and a sequence of row-level calls would let a half-saved arc exist
         *     between two of them.
         */
        put: operations["saveProgramMilestones"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/templates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** Read every message template and the codes they may use */
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/templates/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
                kind: components["schemas"]["TemplateKind"];
            };
            cookie?: never;
        };
        get?: never;
        /** Edit one template */
        put: operations["saveTemplate"];
        post?: never;
        /**
         * Drop the edit and go back to the default wording
         * @description Removes the programme's override. The default text is Braid's, so this
         *     cannot fail with nothing to fall back on.
         */
        delete: operations["resetTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** List applications submitted to a program */
        get: operations["listApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/applications/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide several applications at once
         * @description Bulk approve is the action a coordinator reaches for after reading a
         *     morning's intake, so it is one request rather than a loop the browser
         *     drives. Partial success is reported rather than hidden: `decided` counts
         *     what moved, `skipped` names what did not and why.
         */
        post: operations["decideApplications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve, waitlist or reject one application
         * @description Approving creates the participation that puts someone on the roster.
         *     The transition is one way in this slice: there is no un-approve, because
         *     undoing it would have to decide what happens to a strand they may
         *     already hold.
         */
        post: operations["decideApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/form-versions/{formVersionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                formVersionId: string;
            };
            cookie?: never;
        };
        /**
         * Read one form version by id
         * @description An application stores the id of the version it was answered against, and
         *     answers are keyed by field id. Reading a decided application back
         *     therefore needs that exact version — not the current published one, which
         *     may have moved on — or the answers are a map of uuids to values.
         */
        get: operations["getFormVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/unmatched": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** List everyone in the program with no strand */
        get: operations["listUnmatched"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** List matching runs for a program */
        get: operations["listRuns"];
        put?: never;
        /**
         * Start a matching run
         * @description Returns immediately with state `queued`. A run is a stored object with a
         *     lifecycle, not a function call: poll the run to follow it to `drafted`.
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * Read a run, its fairness summary, and its draft pairs
         * @description While the run is `queued` or `running`, `progress` advances from 0 to 1
         *     and `fairnessSummary` is null. Both are populated once it reaches
         *     `drafted`.
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a drafted run
         * @description Irreversible. Converts every draft pair into an active strand and
         *     notifies both sides.
         */
        post: operations["publishRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/strands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** List the strands the current account holds in a program */
        get: operations["listStrands"];
        put?: never;
        /**
         * Pair two people by hand
         * @description The remedy for most unmatched reasons. Stored with origin mode `manual`
         *     so reports can answer whether the algorithm did better than the
         *     coordinator's hand-picks, which is the whole reason origin mode exists.
         */
        post: operations["createStrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strands/{strandId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        /** Read one strand */
        get: operations["getStrand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strands/{strandId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        /**
         * Read a strand's message thread
         * @description Newest last. Page backwards with `before`.
         */
        get: operations["listMessages"];
        put?: never;
        /** Send a message to a strand */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @description Stable machine-readable identifier, e.g. `applications_closed`. */
            code: string;
            /** @description Sentence-case text safe to show a person. */
            message: string;
            /** @description Present when the failure belongs to one input. */
            field?: string;
        };
        /** @enum {string} */
        Role: "mentor" | "mentee";
        /** @enum {string} */
        ParticipationStatus: "invited" | "applied" | "approved" | "waitlisted" | "removed";
        /** @enum {string} */
        ApplicationStatus: "submitted" | "under_review" | "approved" | "waitlisted" | "rejected";
        /** @enum {string} */
        ProgramState: "not_yet_open" | "open" | "closed" | "full";
        /** @enum {string} */
        RunState: "queued" | "running" | "drafted" | "published" | "discarded";
        /** @enum {string} */
        StrandState: "draft" | "active" | "paused" | "ended" | "discarded";
        /** @enum {string} */
        OriginMode: "manual" | "self" | "batch";
        /** @enum {string} */
        PriorityBand: "high" | "medium" | "low";
        /** @description One answer to one question. */
        AnswerValue: string | number | boolean | string[];
        /**
         * @description Where the words came from. `self` is typed unprompted; `guided` is the
         *     answer to an elicitation follow-up on the guided completion screen.
         *
         *     Recorded because scoring free text rewards writing fluency, which tracks
         *     schooling and language background. Reports have to be able to ask
         *     whether coverage improved without the guided answers quietly becoming a
         *     ranking feature.
         * @enum {string}
         */
        Provenance: "self" | "guided";
        /**
         * @description One answer on the way in. There is no timestamp: the server stamps it,
         *     because a client-supplied time is not evidence of anything.
         */
        AnswerInput: {
            value: components["schemas"]["AnswerValue"];
            provenance: components["schemas"]["Provenance"];
        };
        /** @description One stored answer, as read back. */
        AnswerRecord: {
            value: components["schemas"]["AnswerValue"];
            provenance: components["schemas"]["Provenance"];
            /** Format: date-time */
            answeredAt: string;
        };
        /** @enum {string} */
        FormFieldType: "short_text" | "long_text" | "single_select" | "multi_select" | "scale" | "number" | "date" | "file" | "consent";
        /**
         * @description `id` is what an answer stores. Labels are editable copy and must never be
         *     the key, or fixing a typo would orphan every answer that used it.
         */
        FormOption: {
            /** Format: uuid */
            id: string;
            label: string;
        };
        FormClause: {
            /** Format: uuid */
            fieldId: string;
            /** @enum {string} */
            operator: "equals" | "not_equals" | "includes" | "is_answered" | "gt" | "lt";
            value?: components["schemas"]["AnswerValue"];
        };
        /**
         * @description Every clause must hold. One level deep on purpose: `any` can be added
         *     beside `all` later without migrating a single stored schema.
         */
        FormCondition: {
            all: components["schemas"]["FormClause"][];
        };
        FormField: {
            /**
             * Format: uuid
             * @description Stable for the life of the question, across versions and across
             *     label edits. Answers are keyed by this and never by the label.
             */
            id: string;
            type: components["schemas"]["FormFieldType"];
            label: string;
            help?: string | null;
            required: boolean;
            /** @description Feeds the similarity score. */
            matching: boolean;
            /** @description Feeds the priority score. */
            equity: boolean;
            /** @description Collected, never scored, visible to the coordinator only. */
            admin: boolean;
            visibleWhen?: components["schemas"]["FormCondition"] | null;
            /** @description Select types only. */
            options?: components["schemas"]["FormOption"][] | null;
            text?: {
                minLength?: number | null;
                maxLength?: number | null;
                placeholder?: string | null;
            } | null;
            number?: {
                min?: number | null;
                max?: number | null;
                step?: number | null;
                unit?: string | null;
            } | null;
            scale?: {
                min: number;
                max: number;
                minLabel?: string | null;
                maxLabel?: string | null;
            } | null;
            date?: {
                /** Format: date */
                min?: string | null;
                /** Format: date */
                max?: string | null;
            } | null;
            file?: {
                accept: string[];
                maxSizeBytes: number;
            } | null;
            consent?: {
                /**
                 * @description The sentence next to the checkbox. Separate from `label`, which
                 *     names the question in the coordinator's list.
                 */
                statement: string;
                /** Format: uri */
                documentUrl?: string | null;
            } | null;
            /** @description Multi select only. */
            selection?: {
                min?: number | null;
                max?: number | null;
            } | null;
        };
        FormSection: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string | null;
            fields: components["schemas"]["FormField"][];
        };
        /**
         * @description The whole published document. Stored as one versioned JSONB blob rather
         *     than normalised rows: it is read whole, written whole, and never queried
         *     field by field.
         */
        FormVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            role: components["schemas"]["Role"];
            version: number;
            /** Format: date-time */
            publishedAt?: string | null;
            sections: components["schemas"]["FormSection"][];
        };
        Organisation: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** Format: uri */
            logoUrl?: string | null;
        };
        ProgramPublic: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            organisation: components["schemas"]["Organisation"];
            description: string;
            state: components["schemas"]["ProgramState"];
            /** Format: date */
            cohortStart?: string | null;
            /** Format: date */
            cohortEnd?: string | null;
            /** Format: date-time */
            applicationsCloseAt?: string | null;
            /** Format: date-time */
            matchingOpensAt?: string | null;
            /** @description Plain words, e.g. "About two hours a month for six months". */
            timeCommitment?: string | null;
            eligibility?: string | null;
            openRoles: components["schemas"]["Role"][];
            mentorCount: number;
            menteeCount: number;
            /**
             * @description How many mentees this round can take, from the mentors who have
             *     signed up and the capacity each set.
             */
            capacity?: number | null;
            /**
             * @description Design direction section 9 puts this in the landing hero, and
             *     section 1 requires scarcity to be shown rather than hidden: a full
             *     round says zero rather than dropping the number. Null only where a
             *     programme has not set capacity at all.
             */
            placesRemaining?: number | null;
        };
        ApplicationDraftSave: {
            /**
             * Format: uuid
             * @description Omit on the first save. The server mints one and returns it.
             */
            draftId?: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            formVersionId: string;
            answers: {
                [key: string]: components["schemas"]["AnswerInput"];
            };
        };
        ApplicationDraft: {
            /** Format: uuid */
            draftId: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            formVersionId: string;
            answers: {
                [key: string]: components["schemas"]["AnswerRecord"];
            };
            /**
             * Format: date-time
             * @description What the autosave indicator shows. Section 9: a timestamp, never a
             *     spinner — a spinner says "wait", and the applicant has nothing to
             *     wait for.
             */
            savedAt: string;
        };
        ApplicationCreate: {
            role: components["schemas"]["Role"];
            name: string;
            /** Format: email */
            email: string;
            /**
             * Format: uuid
             * @description Which published version was on screen. Sent so the server can reject
             *     a submission filled against a version that is no longer current,
             *     rather than storing answers to questions nobody can reconstruct.
             */
            formVersionId: string;
            /**
             * @description Keyed by field id. Answers to fields hidden by a condition are not
             *     sent; the client keeps them locally in case the person toggles back,
             *     but an unasked question has no answer.
             */
            answers: {
                [key: string]: components["schemas"]["AnswerInput"];
            };
        };
        Application: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            programName?: string;
            role: components["schemas"]["Role"];
            name: string;
            /** Format: email */
            email: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            decidedAt?: string | null;
            /** @description The coordinator who decided it, for the audit log. */
            decidedBy?: string | null;
            /** Format: date-time */
            editableUntil?: string | null;
            /** Format: date-time */
            matchingOpensAt?: string | null;
            /**
             * Format: uuid
             * @description The version these answers were filled against. Reading them back
             *     without it would mean guessing which questions were asked.
             */
            formVersionId: string;
            answers: {
                [key: string]: components["schemas"]["AnswerRecord"];
            };
        };
        MagicLinkRequest: {
            /** Format: email */
            email: string;
            /** @description Return the person to this program after verifying. */
            orgSlug?: string;
            programSlug?: string;
        };
        VerifyRequest: {
            token: string;
        };
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            emailVerified: boolean;
            /** Format: uri */
            photoUrl?: string | null;
        };
        ParticipationSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            programName: string;
            organisationName?: string;
            orgSlug: string;
            programSlug: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["ParticipationStatus"];
            /** @default false */
            isCoordinator: boolean;
        };
        Session: {
            account: components["schemas"]["Account"];
            participations: components["schemas"]["ParticipationSummary"][];
        };
        RosterEntry: {
            /**
             * Format: uuid
             * @description The participation id, not the account id.
             */
            id: string;
            account: components["schemas"]["Account"];
            role: components["schemas"]["Role"];
            status: components["schemas"]["ParticipationStatus"];
            matched: boolean;
            /** @description Mentors only. How many mentees they will take. */
            capacity?: number | null;
            /** @description Mentors only. Active strands held. May exceed capacity. */
            load?: number | null;
            profileCompleteness: number;
            /** @description IANA name, e.g. Africa/Lagos. */
            timezone?: string | null;
            /** Format: date-time */
            joinedAt: string;
        };
        /**
         * @description Each value is a thing a human has to decide, not a metric. Anything that
         *     resolves itself with time does not belong here.
         * @enum {string}
         */
        AttentionKind: "applications_waiting" | "strands_never_started" | "quiet_strands" | "mentors_over_capacity" | "incomplete_profiles" | "unmatched_people";
        AttentionItem: {
            kind: components["schemas"]["AttentionKind"];
            count: number;
            title: string;
            body?: string | null;
            actionLabel: string;
            /**
             * @description Relative to the programme's admin base, so the server does not have
             *     to know the org slug the coordinator arrived by.
             */
            href: string;
        };
        DashboardSummary: {
            mentorCount: number;
            menteeCount: number;
            /** @description Mentees the programme set out to recruit. Null if none was set. */
            recruitmentGoal?: number | null;
            matchedCount: number;
            unmatchedCount: number;
            activeStrands: number;
            /** @description Active strands with no message for fourteen days. */
            quietStrands: number;
            sessionsLoggedThisWeek: number;
            upcomingMilestone?: components["schemas"]["Milestone"] | null;
            /**
             * @description Ordered by how much it costs to leave alone, not by count. An
             *     empty list is a real and good answer.
             */
            attention: components["schemas"]["AttentionItem"][];
        };
        /**
         * @description Derived from activity, never stored. `not_started` is separated from
         *     `quiet` deliberately: a pair who never began needs an introduction, and
         *     a pair who stopped needs a different conversation.
         * @enum {string}
         */
        StrandHealth: "on_track" | "slow" | "quiet" | "not_started" | "ended";
        StrandMonitorEntry: {
            /** Format: uuid */
            id: string;
            state: components["schemas"]["StrandState"];
            originMode: components["schemas"]["OriginMode"];
            members: components["schemas"]["StrandMember"][];
            /** @description Null when nothing has ever been said. */
            daysSinceActivity?: number | null;
            sessionsLogged: number;
            milestonesCompleted: number;
            milestonesTotal: number;
            health: components["schemas"]["StrandHealth"];
        };
        StrandHealthCounts: {
            on_track: number;
            slow: number;
            quiet: number;
            not_started: number;
            ended: number;
        };
        StrandMonitorPage: {
            items: components["schemas"]["StrandMonitorEntry"][];
            page: number;
            pageSize: number;
            total: number;
            healthCounts: components["schemas"]["StrandHealthCounts"];
        };
        NudgeResult: {
            /** @description How many people the nudge went to. */
            sentTo: number;
        };
        StrandStateChange: {
            /** @enum {string} */
            state: "active" | "paused" | "ended";
            /** @description Recorded against the change for the audit log. */
            reason?: string | null;
        };
        /**
         * @description A point in the programme arc, defined against the cohort start rather
         *     than a calendar date. Cohorts get re-run with new dates and the arc is
         *     the part that stays the same.
         *
         *     Distinct from `Milestone`, which is one participant's resolved instance
         *     of this — that one has a real due date and a done flag.
         */
        ProgramMilestone: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string | null;
            /** @description Weeks after the cohort starts. */
            weekOffset: number;
            /**
             * @description Shown inside every strand when this point is reached. The whole
             *     reason milestones exist rather than living in a coordinator's
             *     calendar: the arc has to reach the people in it.
             */
            strandPrompt?: string | null;
            /** @description Null means no reminder is sent. */
            reminderDaysBefore?: number | null;
            /** @description Order in the arc. Ties on weekOffset are broken by this. */
            position: number;
        };
        ProgramMilestoneInput: {
            /**
             * Format: uuid
             * @description Null for a milestone being added.
             */
            id?: string | null;
            title: string;
            description?: string | null;
            weekOffset: number;
            strandPrompt?: string | null;
            reminderDaysBefore?: number | null;
            position: number;
        };
        ProgramMilestonesSave: {
            items: components["schemas"]["ProgramMilestoneInput"][];
        };
        /** @enum {string} */
        TemplateKind: "welcome" | "match_notification" | "nudge" | "mid_point_check_in" | "closing";
        MessageTemplate: {
            kind: components["schemas"]["TemplateKind"];
            subject: string;
            body: string;
            /**
             * @description True while the programme has not overridden the wording. Shown so a
             *     coordinator can tell what she has written from what she inherited.
             */
            isDefault: boolean;
            /** Format: date-time */
            updatedAt?: string | null;
            updatedBy?: string | null;
        };
        MessageTemplateSave: {
            subject: string;
            body: string;
        };
        MergeCode: {
            /** @description Written in the body as {code}. */
            code: string;
            description: string;
            /**
             * @description What it resolves to in the preview. Carried by the API so the
             *     preview shows the same substitution the sender will perform, rather
             *     than one the browser invented.
             */
            sample: string;
        };
        TemplateSet: {
            items: components["schemas"]["MessageTemplate"][];
            mergeCodes: components["schemas"]["MergeCode"][];
        };
        /**
         * @description The review table's row. Deliberately not the whole Application: a
         *     coordinator scanning a morning's intake does not need every answer
         *     loaded, and the detail screen reads the full record when one is opened.
         */
        ApplicationSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            role: components["schemas"]["Role"];
            name: string;
            /** Format: email */
            email: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            decidedAt?: string | null;
            decidedBy?: string | null;
            /**
             * @description Answered fields over askable ones, for the version this application
             *     was answered against. A low figure is not a reason to reject; it is
             *     a reason to read it first.
             */
            completeness: number;
            /**
             * @description Things worth a second look before deciding, named rather than
             *     scored: an incomplete answer set, a duplicate email, an applicant
             *     who has applied to this program before.
             */
            flags?: components["schemas"]["ApplicationFlag"][];
        };
        /** @enum {string} */
        ApplicationFlag: "incomplete" | "duplicate_email" | "reapplied" | "over_subscribed_role";
        ApplicationPage: {
            items: components["schemas"]["ApplicationSummary"][];
            page: number;
            pageSize: number;
            total: number;
            counts: components["schemas"]["ApplicationCounts"];
        };
        /**
         * @description The whole queue's shape, independent of the current filter, so the tabs
         *     can carry counts without a request each.
         */
        ApplicationCounts: {
            submitted: number;
            under_review: number;
            approved: number;
            waitlisted: number;
            rejected: number;
        };
        /** @enum {string} */
        DecisionKind: "approve" | "waitlist" | "reject";
        ApplicationDecision: {
            decision: components["schemas"]["DecisionKind"];
            /**
             * @description Recorded against the decision for the audit log. Not sent to the
             *     applicant; the message they receive comes from a template.
             */
            note?: string | null;
        };
        BulkDecision: {
            applicationIds: string[];
            decision: components["schemas"]["DecisionKind"];
            note?: string | null;
        };
        BulkDecisionResult: {
            decided: number;
            skipped: components["schemas"]["SkippedDecision"][];
        };
        SkippedDecision: {
            /** Format: uuid */
            applicationId: string;
            reason: string;
        };
        /**
         * @description Every value here has a different remedy, which is why the queue stores a
         *     code rather than a sentence. No capacity needs a mentor; no overlap
         *     needs a different pool or a group; an incomplete profile needs the
         *     participant, not the coordinator.
         * @enum {string}
         */
        UnmatchedReason: "no_mentor_capacity" | "no_skill_overlap" | "joined_after_run" | "incomplete_profile" | "all_candidates_declined";
        UnmatchedEntry: {
            /** Format: uuid */
            participationId: string;
            name: string;
            /** Format: email */
            email?: string;
            role: components["schemas"]["Role"];
            reason: components["schemas"]["UnmatchedReason"];
            profileCompleteness: number;
            timezone?: string | null;
            skills?: string[];
            /** Format: date-time */
            joinedAt: string;
            /**
             * Format: uuid
             * @description The run that left them here, if any has been published.
             */
            lastRunId?: string | null;
        };
        UnmatchedPage: {
            items: components["schemas"]["UnmatchedEntry"][];
            page: number;
            pageSize: number;
            total: number;
            /**
             * @description Mentors with capacity to spare, so a manual pairing can be made
             *     without leaving the queue to go and find one.
             */
            availableMentors: components["schemas"]["AvailableMentor"][];
        };
        AvailableMentor: {
            /** Format: uuid */
            participationId: string;
            name: string;
            load: number;
            capacity: number;
            skills?: string[];
            timezone?: string | null;
        };
        StrandCreate: {
            /** Format: uuid */
            menteeParticipationId: string;
            /** Format: uuid */
            mentorParticipationId: string;
        };
        RosterPage: {
            items: components["schemas"]["RosterEntry"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PersonRef: {
            /** Format: uuid */
            participationId: string;
            name: string;
            /** Format: uri */
            photoUrl?: string | null;
        };
        MentorLoad: {
            mentor: components["schemas"]["PersonRef"];
            load: number;
            capacity: number;
        };
        /**
         * @description The comparison that makes a run defensible: whether high-priority
         *     mentees came out with match quality comparable to low-priority ones.
         */
        PriorityBandStat: {
            band: components["schemas"]["PriorityBand"];
            menteeCount: number;
            meanScore: number;
            medianScore: number;
        };
        ScoreBucket: {
            rangeStart: number;
            rangeEnd: number;
            count: number;
        };
        FairnessSummary: {
            coverageRate: number;
            matchedCount: number;
            unmatchedCount: number;
            totalMentees: number;
            mentorLoad: components["schemas"]["MentorLoad"][];
            priorityBands: components["schemas"]["PriorityBandStat"][];
            scoreDistribution: components["schemas"]["ScoreBucket"][];
        };
        DraftPair: {
            /** Format: uuid */
            id: string;
            mentee: components["schemas"]["PersonRef"];
            mentor: components["schemas"]["PersonRef"];
            score: number;
            priorityBand: components["schemas"]["PriorityBand"];
        };
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            state: components["schemas"]["RunState"];
            /** @description 0 to 1 while queued or running. 1 once drafted. */
            progress: number;
            recipeVersion?: number;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            publishedAt?: string | null;
            publishedBy?: string | null;
            draftedCount?: number;
            publishedCount?: number;
            coverageRate?: number | null;
        };
        RunDetail: components["schemas"]["Run"] & {
            fairnessSummary?: components["schemas"]["FairnessSummary"] | null;
            pairs: components["schemas"]["DraftPair"][];
            unmatchedCount: number;
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            page: number;
            pageSize: number;
            total: number;
        };
        /** @enum {string} */
        NextActionKind: "complete_profile" | "accept_request" | "reply_to_message" | "log_session" | "fill_check_in";
        /**
         * @description The one thing worth doing, chosen by the server. Singular on purpose:
         *     design direction 9 gives home one next-action card and says that if
         *     there is no next action, say so plainly rather than inventing one. A
         *     list of three would be a list of none.
         */
        NextAction: {
            kind: components["schemas"]["NextActionKind"];
            title: string;
            body?: string | null;
            /** @description The verb here is the verb in the resulting toast. */
            actionLabel: string;
            /**
             * @description Relative to the program root. Nothing is done on home; every action
             *     is a link into the page that resolves it.
             */
            href: string;
        };
        Announcement: {
            /** Format: uuid */
            id: string;
            body: string;
            authorName: string;
            /** Format: date-time */
            postedAt: string;
        };
        Milestone: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            dueAt: string;
            completed: boolean;
        };
        HomeSummary: {
            /**
             * Format: date-time
             * @description The date the waiting state is built around. Design direction 1: a
             *     participant signs up in September and is matched in October, and
             *     for those three weeks this date is the whole screen.
             */
            matchingOpensAt?: string | null;
            /**
             * @description Mentors signed up to this program. Shown before matching so the
             *     wait reads as being part of something already populated.
             */
            mentorCount: number;
            strandCount: number;
            profileCompleteness: number;
            nextAction?: components["schemas"]["NextAction"] | null;
            announcement?: components["schemas"]["Announcement"] | null;
            upcomingMilestone?: components["schemas"]["Milestone"] | null;
        };
        StrandMember: {
            /** Format: uuid */
            participationId: string;
            name: string;
            role: components["schemas"]["Role"];
            headline?: string | null;
            /** Format: uri */
            photoUrl?: string | null;
            timezone?: string | null;
            skills?: string[];
        };
        MessagePreview: {
            authorName: string;
            body: string;
            /** Format: date-time */
            sentAt: string;
        };
        StrandSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            state: components["schemas"]["StrandState"];
            originMode: components["schemas"]["OriginMode"];
            /** @description Everyone except the current account. */
            members: components["schemas"]["StrandMember"][];
            lastMessage?: components["schemas"]["MessagePreview"] | null;
            /**
             * Format: date-time
             * @description The UI derives the quiet state from this. There is no health enum,
             *     because a quiet strand is not an error and must not render as one.
             */
            lastActivityAt?: string | null;
            unreadCount: number;
            /** Format: date-time */
            nextSessionAt?: string | null;
            /**
             * Format: date-time
             * @description Set when `state` is `ended`. The card names the date, so the
             *     summary has to carry it rather than making the list fetch each
             *     strand to find out when it finished.
             */
            endedAt?: string | null;
        };
        Strand: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programId: string;
            state: components["schemas"]["StrandState"];
            originMode: components["schemas"]["OriginMode"];
            /** @description Every member, including the current account. */
            members: components["schemas"]["StrandMember"][];
            /**
             * @description Why these people were put together. A partial explanation, not the
             *     explanation: in a global assignment the real reason often involves a
             *     third person. Present it as such.
             */
            matchRationale?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            endedAt?: string | null;
        };
        MessageCreate: {
            body: string;
            /**
             * @description Echoed back on the created message so an optimistic send can be
             *     reconciled against the server row instead of duplicated.
             */
            clientToken?: string;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            strandId: string;
            author: components["schemas"]["PersonRef"];
            body: string;
            /** Format: date-time */
            sentAt: string;
            /** @enum {string} */
            deliveryState: "sent" | "delivered";
            clientToken?: string | null;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            /** @description Pass as `before` to fetch the previous page. Null when at the start. */
            nextCursor: string | null;
        };
    };
    responses: {
        /** @description The request failed validation */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description No valid session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Signed in, but not permitted here */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limited */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        OrgSlug: string;
        ProgramSlug: string;
        ProgramId: string;
        RunId: string;
        StrandId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProgramBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The program */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramPublic"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getFormSchema: {
        parameters: {
            query: {
                role: components["schemas"]["Role"];
            };
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published form version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormVersion"];
                };
            };
            /** @description No such program, or no published form for that role */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    submitApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Application received */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Applications are closed, or this email already applied */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    joinWaitlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    role?: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getApplicationDraft: {
        parameters: {
            query: {
                draftId: string;
            };
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDraft"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    saveApplicationDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["OrgSlug"];
                programSlug: components["parameters"]["ProgramSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationDraftSave"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDraft"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Applications are closed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The application */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Accepted. A link is sent only if the address has an account. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    verifyMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Session opened */
            200: {
                headers: {
                    /** @example braid_session=…; HttpOnly; Secure; SameSite=Lax; Path=/ */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Token expired or already used */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    /** @example braid_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The home summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRoster: {
        parameters: {
            query?: {
                role?: components["schemas"]["Role"];
                status?: components["schemas"]["ParticipationStatus"];
                /** @description Filter to participants who do or do not hold a strand. */
                matched?: boolean;
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the roster */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dashboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    monitorStrands: {
        parameters: {
            query?: {
                health?: components["schemas"]["StrandHealth"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of strands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrandMonitorPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    nudgeStrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued for delivery */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NudgeResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The strand has ended, so there is nobody to nudge */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setStrandState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrandStateChange"];
            };
        };
        responses: {
            /** @description The strand in its new state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strand"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description That transition is not allowed from the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listProgramMilestones: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The milestones, in the order they happen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramMilestone"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    saveProgramMilestones: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramMilestonesSave"];
            };
        };
        responses: {
            /** @description The saved arc, with ids minted for anything new */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramMilestone"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The templates, with the merge codes available to them */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateSet"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    saveTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
                kind: components["schemas"]["TemplateKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageTemplateSave"];
            };
        };
        responses: {
            /** @description The saved template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplate"];
                };
            };
            /**
             * @description The body used a merge code that does not exist. Rejected rather than
             *     sent, because the failure would otherwise reach a participant as a
             *     literal brace in an email.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    resetTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
                kind: components["schemas"]["TemplateKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The template, restored to its default */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listApplications: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"];
                role?: components["schemas"]["Role"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    decideApplications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDecision"];
            };
        };
        responses: {
            /** @description The outcome of each application in the request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDecisionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    decideApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationDecision"];
            };
        };
        responses: {
            /** @description The application in its new state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The application has already been decided */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getFormVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                formVersionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The form version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormVersion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUnmatched: {
        parameters: {
            query?: {
                reason?: components["schemas"]["UnmatchedReason"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of unmatched participants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnmatchedPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of runs, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A run is already in progress for this program */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    publishRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Run is not in a publishable state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listStrands: {
        parameters: {
            query?: {
                state?: components["schemas"]["StrandState"];
            };
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The strands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrandSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createStrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrandCreate"];
            };
        };
        responses: {
            /** @description The strand, active immediately */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strand"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description One of the two already holds a strand, or the mentor is full */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getStrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The strand */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strand"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Return messages sent before this message id. */
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strandId: components["parameters"]["StrandId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Message sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
